Description: CloudFormation template for initializing CloudWatch Alarms
Parameters:
  SpendingAlarmThreshold:
    Description: "The threshold to trigger the spending alarm."
    Type: Number
    Default: 20
Resources:
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AlarmSNSTopic
      Subscription:
        - Endpoint: shay.luke17+aws@gmail.com
          Protocol: EMAIL
  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub Alarm if AWS spending is over $${SpendingAlarmThreshold}
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: !Ref SpendingAlarmThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions: [!Ref AlarmSNSTopic]
  TestCustom:
    Type: Custom::TestCustom
    Properties:
      ServiceToken: !ImportValue SubValues-Arn
      Value: "${Import::CanvasV2-api-APIUrl} ${Import::CanvasV2-api-APIUrl} ${Import::CanvasV2-api-APIID} ${SpendingAlarmThreshold}"
      SpendingAlarmThreshold: !Ref SpendingAlarmThreshold
Outputs:
  SubValues:
    Description: SubValues test
    Value:
      Fn::Sub:
        - !GetAtt TestCustom.Plaintext
  SubValuesRef:
    Description: SubValues test
    Value: !Ref TestCustom
