Description: CloudFormation template for initializing AWS IAM
Resources:
  AdminUserGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  StandardUserGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
  ReadOnlyUserGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
  GithubCloudFormationUserGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
  LukeShay:
    Type: AWS::IAM::User
    Properties:
      UserName: lukeshay
      Groups:
        - !Ref AdminUserGroup
      LoginProfile:
        Password: "{{resolve:secretsmanager:DefaultUserPassword:SecretString:DefaultUserPassword}}"
        PasswordResetRequired: true
    DependsOn: AdminUserGroup
  GithubCloudFormationUser:
    Type: AWS::IAM::User
    Properties:
      UserName: github-cloudformation-user
      Groups:
        - !Ref GithubCloudFormationUserGroup
    DependsOn: GithubCloudFormationUserGroup
  GithubCloudFormationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GithubCloudFormationUser
      Status: Inactive
    DependsOn: GithubCloudFormationUser
Outputs:
  TemplateID:
    Description: "Template id."
    Value: "security/account-password-policy"
  TemplateVersion:
    Description: "Template version."
    Value: "__VERSION__"
  StackName:
    Description: "Stack name."
    Value: !Sub "${AWS::StackName}"
